name: geoflutterfire
description: GeoFlutterFire is an open-source library that allows you to store and query firestore documents based on their geographic location.
version: 3.0.3
homepage: https://github.com/DarshanGowda0/GeoFlutterFire

environment:
  sdk: ^3.10.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^6.1.1
  rxdart: ^0.28.0

dev_dependencies:
  flutter_test:
    sdk: flutter
